# For home directory compatibility

SHELL := /bin/bash
WS := ./sys_ws

.PHONY: default clean build unspecified
default: unspecified

unspecified:
	cd systems_2023_24 ; $(MAKE) $@


clean:
	cd systems_2023_24 ; $(MAKE) $@

build:
	cd systems_2023_24 ; $(MAKE) $@

#### MISSIONS

# retrieval_mission: copy_conf
# 	@python3 multi-runner.py "make gui" "make drive" "make arm" "make televideo" "make gps"

science_mission:
	cd systems_2023_24 ; $(MAKE) $@

equipment_mission:
	cd systems_2023_24 ; $(MAKE) $@

autonomy_mission:
	cd systems_2023_24 ; $(MAKE) $@

#### HEARTBEAT

heartbeat:
	cd systems_2023_24 ; $(MAKE) $@

#### GUI

gui:
	cd systems_2023_24 ; $(MAKE) $@

gui_frontend:
	cd systems_2023_24 ; $(MAKE) $@

gui_backend:
	# TODO: Need to run script to get databases first?
	cd systems_2023_24 ; $(MAKE) $@

#### DRIVE

drive:
	cd systems_2023_24 ; $(MAKE) $@

drive_rover:
	cd systems_2023_24 ; $(MAKE) $@

drive_base:
	cd systems_2023_24 ; $(MAKE) $@

#### ARM

arm:
	cd systems_2023_24 ; $(MAKE) $@

arm_rover:
	cd systems_2023_24 ; $(MAKE) $@

arm_base:
	cd systems_2023_24 ; $(MAKE) $@

#### TELECOM

televideo:
	cd systems_2023_24 ; $(MAKE) $@

televideo_base:
	cd systems_2023_24 ; $(MAKE) $@

televideo_rover:
	cd systems_2023_24 ; $(MAKE) $@


#### GPS

gps:
	cd systems_2023_24 ; $(MAKE) $@

gps_base:
	cd systems_2023_24 ; $(MAKE) $@

gps_rover:
	cd systems_2023_24 ; $(MAKE) $@


#### SCIENCE

science:
	cd systems_2023_24 ; $(MAKE) $@

#### AUTONOMY

# TODO!!!
autonomy:
	cd systems_2023_24 ; $(MAKE) $@


#### SCP Functions

scp_orin:
	cd systems_2023_24 ; $(MAKE) $@

scp_pi:
	cd systems_2023_24 ; $(MAKE) $@

ssh_orin:
	cd systems_2023_24 ; $(MAKE) $@

ssh_pi:
	cd systems_2023_24 ; $(MAKE) $@